
$(function() {

    // Populate using an object literal
    // Used for making new stuff on my laptop

    // WTF.init({

    //     heading: [
    //         "In the middle of winter a man stumbles into the party. He thrusts a paper into one of their hands saying to keep it safe.",
    //         "In the spring time as the snow melts one of the party members uncovers a secret.",
    //         "Summer time is always hot, unfortunately this summer is not like the last. snow still covers the ground.",
    //         "Talk of war has been whispered for the past year. It will break out any moment.",
    //         "The wilds lands beyond the borders of the kingdom promise new riches and a new life for those who wish to leave their old one behind.",
    //         "Shadows have been seen in the woods, people are starting to disappear at night.",
    //         "No one likes their jobs, but it is the only way to stay alive.",
    //         "The king is offering a great reward for adventurers who are able to bring back something special for him.",
    //         "The baron has a secret that has been buried deep in the earth. Unfortunately when he went looking for it again it was no where to be found. Only foot steps leading away."
    //     ],
    //     response: [
    //         "Click for new campaign.",       
    //     ],
    //     template: [
    //         "The players are @occupationpl looking for @lookingFor. On their way they meet @mentor. They @help. But, @tragedy. The party learns that @evilIntroduction. It all culminates @bossFight.",
    //         "The players are @occupationpl looking for @lookingFor. @evilIntroduction. While fleeing they meet @mentor. But, @tragedy. The final battle happens @bossFight.",
    //     ],
    //     occupationpl: [
    //         "adventurers",
    //         "thieves",
    //         "bounty hunters",
    //         "hunters",
    //         "nobles",
    //         "minor nobles",
    //         "townsfolk",
    //         "peasants",
    //         "guards",
    //         "servants to a wizard",
    //         "slaves",
    //         "part of a wizard's tower",
    //         "treasure hunters",
    //         "archeologists",
    //         "hired muscle"
    //     ],
    //     lookingFor: [
    //         "their mentor",
    //         "gold",
    //         "treasure",
    //         "a secret book",
    //         "a map to a treasure",
    //         "a map to a secret underground lair",
    //         "the last of a mystical beast",
    //         "their teacher",
    //         "their inheritance",
    //         "the lost treasure of a forgotten civilization",
    //         "a forgotten treasure hoard",
    //         "the book of secrets",
    //         "a powerful spellbook",
    //         "the lost amulet",
    //         "a magical set of armor",
    //         "a shard of elemental energy"
    //     ],
    //     mentor: [
    //         "a wise old wizard who teaches them a magic spell",
    //         "a kindly woman who teaches them a magic spell",
    //         "an unlikely troll who teaches them a magic spell",
    //         "a skilled fighter who teaches them a magic spell",
    //         "a druid in the forest who teaches them a magic spell",
    //         "a wise old wizard who feeds them a magnificent dinner",
    //         "a kindly woman who feeds them a magnificent dinner",
    //         "an unlikely troll who feeds them a magnificent dinner",
    //         "a skilled fighter who feeds them a magnificent dinner",
    //         "a druid in the forest who feeds them a magnificent dinner",
    //         "a wise old wizard who gives them each a weapon",
    //         "a kindly woman who gives them each a weapon",
    //         "an unlikely troll who teaches them the value of friendship",
    //         "a skilled fighter who gives them each a weapon",
    //         "a druid in the forest who gives them each a weapon",
    //         "a wise old wizard who rescues them from a frightening animal",
    //         "a kindly woman who rescues them from a frightening animal",
    //         "an unlikely troll who rescues them from a frightening animal",
    //         "a skilled fighter who rescues them from a frightening animal",
    //         "a druid in the forest who rescues them from a frightening animal",
    //     ],
    //     treasure: [
    //         "gold",
    //         "magical weapons",
    //         "a hidden book of secrets",
    //         "pocket lint",
    //         "a sword",
    //         "a suit of armor",
    //         "a portal to another plane",
    //         "gems"
    //     ],
    //     tragedy: [
    //         "a party member is bitten by a werewolf",
    //         "a party member's loved one dies",
    //         "the path is washed out and a new way is needed",
    //         "the forest is overgrown and will take twice as long to get through",
    //         "a message comes that a character's loved one is dying",
    //         "during the night a thief steals all their money",  
    //         "the reach their destination only to find it burnt to the ground",
    //         "their friend dies in combat",
    //         "their traveling companion is mortally wounded",
    //         "their traveling companion betrays them"
    //     ],
    //     help: [
    //         "heal the party",
    //         "guide the party",
    //         "hide the party from their enemies",
    //         "write to a powerful person in the next town giving the party anything they need for the journey",
    //         "transport the party half way along their journey",
    //         "give the party supplies for the journey",
    //         "give the party a magic spellbook"
    //     ],
    //     evilIntroduction: [
    //         "a beholder has been sending monsters after them",
    //         "an undead revenant is pursuing them",
    //         "an owlbear is pursuing them",
    //         "an orc tribe is pursuing them",
    //         "a devil is pursuing them",
    //         "an army is pursuing them",
    //         "an evil wizard has been watching them and plans to steal what they are after",
    //         "an necromancer has been watching them and plans to steal what they are after",
    //         "a bugbear has been watching them and plans to steal what they are after",
    //         "an pirate king has been watching them and plans to steal what they are after",
    //         "an sorcerer has been watching them and plans to steal what they are after",
    //         "an agent of darkness has been watching them and plans to steal what they are after",
    //         "the king has put a bounty on their heads and every man woman and child with a weapon is on the look out for them",
    //         "the queen has put a bounty on their heads and every man woman and child with a weapon is on the look out for them",
    //         "the baron has put a bounty on their heads and every man woman and child with a weapon is on the look out for them",
    //         "the baroness has put a bounty on their heads and every man woman and child with a weapon is on the look out for them",
    //         "their destination has been taken over by gnolls",
    //         "their destination has been taken over by aberrations",
    //         "their destination has been taken over by devils",
    //         "their destination has been taken over by duergar",
    //         "their destination has been taken over by bandits",
    //         "their destination has been taken over by a dragon",
    //         "their home town has been overrun by a hobgoblin and their clan",
    //         "their home town has been overrun by a bandits and their dogs",
    //         "their home town has been overrun by a devils and their slaves",
    //         "their home town has been overrun by a cultists and their prophet",
    //         "their home town has been overrun by a beasts from the forest",
    //         "a dragon has made a lair in the party's destination",
    //         "a beholder has made a lair in the party's destination",
    //         "a litch has made a lair in the party's destination",
    //         "a demon has made a lair in the party's destination",
    //         "a devil has made a lair in the party's destination",
    //         "an abomination has made a lair in the party's destination",
    //         "a necromancer has heard tale of their deeds and is setting a trap for them",  
    //         "a wizard has heard tale of their deeds and is setting a trap for them",  
    //         "a thief has heard tale of their deeds and is setting a trap for them",  
    //         "a hobgoblin has heard tale of their deeds and is setting a trap for them",  
    //         "a mindflayer has heard tale of their deeds and is setting a trap for them",  
    //         "a drow has heard tale of their deeds and is setting a trap for them",            
    //         "a gnome has heard tale of their deeds and is setting a trap for them"
    //     ],
    //     bossFight: [
    //         "in the lair of a monstrous beast",
    //         "in the lair of a dragon",
    //         "at home fighting for their loves ones' freedom",
    //         "on a icy mountain peak struggling against the elements",
    //         "on a icy mountain peak fighting a dragon",
    //         "in a volcano struggling against the elements",
    //         "in a volcano fighting a dragon",
    //         "deep underground in the dark at the mouth of a portal",
    //         "deep underground in the dark with the echoing sounds of battle",
    //         "in a ruined temple to a forgotten god filled with gnolls",
    //         "in a ruined temple to a forgotten god filled with devils",
    //         "in a ruined temple to a forgotten god filled with demons",
    //         "in a ruined temple to a forgotten god filled with goblins",
    //         "in a ruined temple to a forgotten god filled with kobolds",
    //         "in a ruined temple to a forgotten god filled with traps",
    //         "in a ruined temple to a forgotten god filled with orcs",
    //         "in a ruined castle filled with orcs",
    //         "in a ruined castle filled with gnolls",
    //         "in a ruined castle filled with devils",
    //         "in a ruined castle filled with demons",
    //         "in a ruined castle filled with goblins",
    //         "in a ruined castle filled with kobolds",
    //         "in a ruined castle filled with traps",
    //         "in a ruined tower filled with orcs",
    //         "in a ruined tower filled with gnolls",
    //         "in a ruined tower filled with devils",
    //         "in a ruined tower filled with demons",
    //         "in a ruined tower filled with goblins",
    //         "in a ruined tower filled with kobolds",
    //         "in a ruined tower filled with traps",
    //         "in a town where everyone is suspicious of them",
    //         "in a town where everyone is suspicious of them",
    //         "out in the grassy plains exposed on all sides to enemies",
    //         "in the town center exposed on all sides to enemies",
    //         "running for their lives out of a mausoleum",
    //         "running for their lives out of a temple",
    //         "in a ruined temple that was sealed shut, not to keep people out, but to keep its occupant sealed in",
    //         "in a ruined shrine that was sealed shut, not to keep people out, but to keep its occupant sealed in",
    //     ]
        
    // });

    // Populate using a JSON file
     WTF.init('campaignContent.json');
    // needs to have a web server for ajax. https://stackoverflow.com/questions/19706046/how-to-read-an-external-local-json-file-in-javascript

    
    // // Populate using a Google spreadsheet ID (you must publish it first!)
    // @see https://support.google.com/drive/answer/37579?hl=en
    // WTF.init( '0AvG1Hx204EyydF9ub1M2cVJ3Z1VGdDhTSWg0ZV9LNGc' );

});
